version: '3.8'

networks:
  net:

services:
  db:
    image: postgres:13.2
    networks:
      net:
        aliases: 
          - db
    environment: 
      - POSTGRES_DB=cars_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cars:
    networks:
      net:
        aliases: 
          - cars
    environment: 
      - DATABASE_URL=postgres://postgres:postgres@db:5432/cars_db
    build: .
    container_name: cars
    command: >
      bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./cars/:/app/cars/
      - ./cars_api/:/app/cars_api/
      - ./Pipfile:/app/Pipfile
      - ./Pipfile.lock:/app/Pipfile.lock
      - ./static/:/app/static/
      - ./templates/:/app/templates/
    ports:
      - "8000:8000"
    depends_on: 
      - db
