version: '3.8'

networks:
  net:

services: 
  cars:
    networks:
      net:
        aliases: 
          - cars
    environment: 
      - DJANGO_KEY="=0ay5hg4ee_em4+s-(@y4csvnyks)b6i8sxvjlwc*e)fa_w(%="
    build: .
    container_name: cars
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/app/
      - ./Pipfile:/Pipfile
      - ./Pipfile.lock:/Pipfile.lock
    ports:
      - "8000:8000"
